### ISSUE TITLE
divSpectrums ambiguous overload

### ISSUE THREAD

**Issue by maulanaazhari** [ctu-mrs/mrs_optic_flow#3]
failed to compile the code due to ambiguous function (similar to opencv function)

`
tArray, int, bool)’
 1086 | static void divSpectrums(cv::InputArray _srcA, cv::InputArray _srcB, cv::OutputArray _dst, int flags, bool conjB) {
      |             ^~~~~~~~~~~~
In file included from /usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp:48,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/include/FftMethod.h:7,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1:
/usr/local/include/opencv4/opencv2/imgproc.hpp:2990:19: note: candidate: ‘void cv::divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 2990 | CV_EXPORTS_W void divSpectrums(InputArray a, InputArray b, OutputArray c,
      |                   ^~~~~~~~~~~~
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1496:48: error: call of overloaded ‘divSpectrums(cv::Mat&, cv::Mat&, cv::Mat&, int, bool)’ is ambiguous
 1496 |           divSpectrums(H_P, H_Pm, H_D, 0, false);  // FF* / |FF*| (phase correlation equation completed here...)
      |                                                ^
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1086:13: note: candidate: ‘void divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 1086 | static void divSpectrums(cv::InputArray _srcA, cv::InputArray _srcB, cv::OutputArray _dst, int flags, bool conjB) {
      |             ^~~~~~~~~~~~
In file included from /usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp:48,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/include/FftMethod.h:7,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1:
/usr/local/include/opencv4/opencv2/imgproc.hpp:2990:19: note: candidate: ‘void cv::divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 2990 | CV_EXPORTS_W void divSpectrums(InputArray a, InputArray b, OutputArray c,
      |                   ^~~~~~~~~~~~
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp: In member function ‘std::vector<cv::Point_<double> > FftMethod::phaseCorrelateFieldLongRange(cv::Mat&, cv::Mat&, unsigned int, unsigned int, double*)’:
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1639:42: error: call of overloaded ‘divSpectrums(cv::UMat&, cv::UMat&, cv::UMat&, int, bool)’ is ambiguous
 1639 |           divSpectrums(P, Pm, C, 0, false);  // FF* / |FF*| (phase correlation equation completed here...)
      |                                          ^
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1086:13: note: candidate: ‘void divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 1086 | static void divSpectrums(cv::InputArray _srcA, cv::InputArray _srcB, cv::OutputArray _dst, int flags, bool conjB) {
      |             ^~~~~~~~~~~~
In file included from /usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp:48,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/include/FftMethod.h:7,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1:
/usr/local/include/opencv4/opencv2/imgproc.hpp:2990:19: note: candidate: ‘void cv::divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 2990 | CV_EXPORTS_W void divSpectrums(InputArray a, InputArray b, OutputArray c,
      |                   ^~~~~~~~~~~~
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1652:48: error: call of overloaded ‘divSpectrums(cv::Mat&, cv::Mat&, cv::Mat&, int, bool)’ is ambiguous
 1652 |           divSpectrums(H_P, H_Pm, H_D, 0, false);  // FF* / |FF*| (phase correlation equation completed here...)
      |                                                ^
/home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1086:13: note: candidate: ‘void divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 1086 | static void divSpectrums(cv::InputArray _srcA, cv::InputArray _srcB, cv::OutputArray _dst, int flags, bool conjB) {
      |             ^~~~~~~~~~~~
In file included from /usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp:48,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/include/FftMethod.h:7,
                 from /home/usrg/mbz_ws/src/mrs_optic_flow/src/FftMethod.cpp:1:
/usr/local/include/opencv4/opencv2/imgproc.hpp:2990:19: note: candidate: ‘void cv::divSpectrums(cv::InputArray, cv::InputArray, cv::OutputArray, int, bool)’
 2990 | CV_EXPORTS_W void divSpectrums(InputArray a, InputArray b, OutputArray c,
      |                   ^~~~~~~~~~~~
make[2]: *** [mrs_optic_flow/CMakeFiles/OpticFlow.dir/build.make:104: mrs_optic_flow/CMakeFiles/OpticFlow.dir/src/FftMethod.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:15562: mrs_optic_flow/CMakeFiles/OpticFlow.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Invoking "make -j20 -l20" failed
`

**Comment by cturmrsbot** [comment]
It builds on my machine (20.04) and under our Singularity (https://github.com/ctu-mrs/mrs_singularity/). However, this package is kinda old, and we are not planning on using it anymore. So it is not integrated into the MRS UAV System anymore. I have pushed a minor update that fixes the launch file and configs a little bit, so you should be able to run it if you really need it.

**Comment by maulanaazhari** [comment]
@cturmrsbot thanks for your quick response, I would definitely check out the Singularity!
